security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # in_memory: { memory: null }
        app_user_provider:
            entity:
                class: App\Entity\Participant
                property: pseudo
    encoders:
        # Pour l'encodage du mot de passe
        App\Entity\Participant:
            algorithm: bcrypt
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            # anonymous: true
            anonymous: ~
            pattern: ^/
            provider: app_user_provider
            # Pour le login
            form_login:
                # Nom de la route
                login_path: connexion
                check_path: connexion
            logout_on_user_change: true
            logout:
                path: deconnexion
                target: connexion
            remember_me:
                name: remember_me
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                secure: true
                path: /
            access_denied_handler: App\Security\AccessDeniedHandler

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
    access_control:
        - { path: ^/inscription, roles: ROLE_ADMIN }
        - { path: ^/profil, roles: ROLE_USER }
        - { path: ^/refreshSorties, roles: ROLE_USER }
        - { path: ^/motdepasseoubli, roles: ROLE_USER }
        - { path: ^/liste, roles: ROLE_ADMIN }
        - { path: ^/ban, roles: ROLE_ADMIN }
        - { path: ^/unban, roles: ROLE_ADMIN }
        - { path: ^/remove, roles: ROLE_ADMIN }
        - { path: ^/inscrire, roles: ROLE_USER }
        - { path: ^/desinscrire, roles: ROLE_USER }
        - { path: ^/publier, roles: ROLE_USER }
        - { path: ^/annuler, roles: ROLE_USER }
        - { path: ^/creer, roles: ROLE_USER }
        - { path: ^/majLieux, roles: ROLE_USER }
        - { path: ^/majInfoLieu, roles: ROLE_USER }
        - { path: ^/sortie, roles: ROLE_USER }
        - { path: ^/groupes, roles: ROLE_USER }
        - { path: ^/lieux, roles: ROLE_USER }
        - { path: ^/ville, roles: ROLE_ADMIN }
        - { path: ^/lieuCreation, roles: ROLE_USER }
